package nanoid

const (
	CHARACTERS_NUMBERS    = "0123456789"
	CHARACTERS_LOWERCASE  = "abcdefghijklmnopqrstuvwxyz"
	CHARACTERS_UPPERCASE  = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	CHARACTERS_SYMBOLS    = "_-"
	CHARACTERS_LOOK_ALIKE = "1lI0Oouv5Ss"

	SAFE_LENGTH = 21
)
